### ISSUE TITLE
Embedded drawio has line anti-aliasing problem

### ISSUE THREAD

**Issue by wkvolkman** [deathbeds/ipydrawio#10]
This appears to have been fixed in their 13.7.3 release which is pretty new.  Great job on the other aspects of the interface.  I was hoping I could use this with the junior DBAs to document our procedures.  Keep up the good work.

**Comment by wkvolkman** [comment]
nit: In the examples for the doc export the conda install should be "nodejs==12"?

Tried to build but get the following
```bash
(base) [wkv@wkv6 jupyterlab-drawio]$ doit all
Traceback (most recent call last):
  File "/home/wkv/anaconda3/lib/python3.7/site-packages/doit/doit_cmd.py", line 190, in run
    return command.parse_execute(args)
  File "/home/wkv/anaconda3/lib/python3.7/site-packages/doit/cmd_base.py", line 150, in parse_execute
    return self.execute(params, args)
  File "/home/wkv/anaconda3/lib/python3.7/site-packages/doit/cmd_base.py", line 554, in execute
    self.loader.setup(params)
  File "/home/wkv/anaconda3/lib/python3.7/site-packages/doit/cmd_base.py", line 420, in setup
    opt_values['seek_file'],
  File "/home/wkv/anaconda3/lib/python3.7/site-packages/doit/loader.py", line 95, in get_module
    return importlib.import_module(os.path.splitext(file_name)[0])
  File "/home/wkv/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/wkv/projects/wkvtools/jupyterlab-drawio/dodo.py", line 7, in <module>
    import scripts.project as P
ModuleNotFoundError: No module named 'scripts.project'
(base) [wkv@wkv6 jupyterlab-drawio]$ git pull
Already up-to-date.
(base) [wkv@wkv6 jupyterlab-drawio]$ conda search scripts
Loading channels: done
No match found for: scripts. Search: *scripts*

PackagesNotFoundError: The following packages are not available from current channels:

  - scripts

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


(base) [wkv@wkv6 jupyterlab-drawio]$ conda search scripts -c conda-forge
Loading channels: done
No match found for: scripts. Search: *scripts*
# Name                       Version           Build  Channel             
lbscriptslegacy                0.1.2    pyh9f0ad1d_0  conda-forge         
ligotools-scripts              1.2.0               0  conda-forge         
ligotools-scripts              1.2.0               1  conda-forge         
pytest-console-scripts           0.1.4            py_0  conda-forge         
pytest-console-scripts           0.1.5            py_0  conda-forge         
pytest-console-scripts           0.1.8            py_0  conda-forge         
pytest-console-scripts           0.1.9            py_0  conda-forge         
pytest-console-scripts           0.2.0            py_0  conda-forge    ```

**Comment by bollwyvl** [comment]
@wkvolkman Really sorry I didn't respond to this! Some stuff got complicated in the mimerender work on #9, and I kinda lost steam for a while. 

But... 

We just got the newly-rebranded `ipydrawio`, which is includes `drawio 14.2.6`, as a JupyterLab 3 federated extension, so no more `ENOENT` nonsense when installing this beast, so if you're conda-forward:

```bash
pip install ipydrawio=1.0.0a0 # and/or ipydrawio-export, if you're brave
```

As always with this project, there's lots of shiny, sharp edges. Thanks for taking the ride! :roller_coaster: 

Side note: while we'll still be shipping the `npm` tarballs for downstreams to play with, the source-based install with e.g. `jupyter labextension install @deathbeds/ipydrawio` is no longer tested.

To your other piece: the `doit` stuff is just for dev against a live checkout... the released versions don't require it (or know about my crazy, dirty `scripts` :blush: )


I'll close this, but please re-open if the anti-aliasing issue is not solved!
